Repository GoogleCloudPlatform/public-datasets-pipelines, pull requests merged in 2021-11, with the labels that each got.

#224 fix: Set `location` field as required for GCS buckets
  samples/dataset.yaml
Labels: bug, cla: yes

#227 fix: Namespace Terraform resources under dataset names
  datasets/austin_waste/_terraform/waste_and_diversion_pipeline.tf
  datasets/bls/_terraform/c_cpi_u_pipeline.tf
  datasets/bls/_terraform/cpi_u_pipeline.tf
  datasets/bls/_terraform/employment_hours_earnings_pipeline.tf
  datasets/bls/_terraform/employment_hours_earnings_series_pipeline.tf
  datasets/bls/_terraform/unemployment_cps_pipeline.tf
  datasets/bls/_terraform/unemployment_cps_series_pipeline.tf
  datasets/bls/_terraform/wm_pipeline.tf
  datasets/bls/_terraform/wm_series_pipeline.tf
  datasets/chicago_crime/_terraform/crime_pipeline.tf
  datasets/world_bank_intl_education/_terraform/country_series_definitions_pipeline.tf
  datasets/world_bank_intl_education/_terraform/country_summary_pipeline.tf
  datasets/world_bank_intl_education/_terraform/series_summary_pipeline.tf
Labels: cleanup, cla: yes

#226 Fix: Renamed dataset from `sunroof` to `sunroof_solar`
  datasets/sunroof/_terraform/sunroof_dataset.tf
  datasets/sunroof_solar/_images/run_csv_transform_kub/Dockerfile
  datasets/sunroof_solar/_images/run_csv_transform_kub/csv_transform.py
  datasets/sunroof_solar/_images/run_csv_transform_kub/requirements.txt
  datasets/sunroof_solar/_terraform/provider.tf
  datasets/sunroof_solar/_terraform/solar_potential_by_censustract_pipeline.tf
  datasets/sunroof_solar/_terraform/solar_potential_by_postal_code_pipeline.tf
  datasets/sunroof_solar/_terraform/sunroof_solar_dataset.tf
  datasets/sunroof_solar/_terraform/variables.tf
  datasets/sunroof_solar/dataset.yaml
  datasets/sunroof_solar/solar_potential_by_censustract/pipeline.yaml
  datasets/sunroof_solar/solar_potential_by_censustract/solar_potential_by_censustract_dag.py
  datasets/sunroof_solar/solar_potential_by_postal_code/pipeline.yaml
  datasets/sunroof_solar/solar_potential_by_postal_code/solar_potential_by_postal_code_dag.py
Labels: bug, data onboarding, cla: yes

#229 feat: Support CloudDataTransferServiceGCSToGCSOperator
  Pipfile
  Pipfile.lock
  samples/pipeline.yaml
  scripts/dag_imports.json
Labels: feature request, cla: yes

#219 feat: Onboard Cloud Storage Geo Index Dataset
  datasets/cloud_storage_geo_index/_images/run_csv_transform_kub/Dockerfile
  datasets/cloud_storage_geo_index/_images/run_csv_transform_kub/csv_transform.py
  datasets/cloud_storage_geo_index/_images/run_csv_transform_kub/requirements.txt
  datasets/cloud_storage_geo_index/_terraform/cloud_storage_geo_index_dataset.tf
  datasets/cloud_storage_geo_index/_terraform/landsat_index_pipeline.tf
  datasets/cloud_storage_geo_index/_terraform/provider.tf
  datasets/cloud_storage_geo_index/_terraform/sentinel_2_index_pipeline.tf
  datasets/cloud_storage_geo_index/_terraform/variables.tf
  datasets/cloud_storage_geo_index/dataset.yaml
  datasets/cloud_storage_geo_index/landsat_index/landsat_index_dag.py
  datasets/cloud_storage_geo_index/landsat_index/pipeline.yaml
  datasets/cloud_storage_geo_index/sentinel_2_index/pipeline.yaml
  datasets/cloud_storage_geo_index/sentinel_2_index/sentinel_2_index_dag.py
Labels: cla: yes

#230 Feat: Onboard IDC PDP datasets
  datasets/idc/_images/copy_bq_datasets/Dockerfile
  datasets/idc/_images/copy_bq_datasets/requirements.txt
  datasets/idc/_images/copy_bq_datasets/script.py
  datasets/idc/_images/generate_bq_views/Dockerfile
  datasets/idc/_images/generate_bq_views/queries/.DS_Store
  datasets/idc/_images/generate_bq_views/queries/v1/dicom_all.sql
  datasets/idc/_images/generate_bq_views/queries/v1/measurement_groups.sql
  datasets/idc/_images/generate_bq_views/queries/v1/qualitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v1/quantitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v1/segmentations.sql
  datasets/idc/_images/generate_bq_views/queries/v2/dicom_all.sql
  datasets/idc/_images/generate_bq_views/queries/v2/measurement_groups.sql
  datasets/idc/_images/generate_bq_views/queries/v2/qualitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v2/quantitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v2/segmentations.sql
  datasets/idc/_images/generate_bq_views/queries/v3/dicom_all.sql
  datasets/idc/_images/generate_bq_views/queries/v3/measurement_groups.sql
  datasets/idc/_images/generate_bq_views/queries/v3/qualitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v3/quantitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v3/segmentations.sql
  datasets/idc/_images/generate_bq_views/queries/v4/dicom_all.sql
  datasets/idc/_images/generate_bq_views/queries/v4/measurement_groups.sql
  datasets/idc/_images/generate_bq_views/queries/v4/qualitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v4/quantitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v4/segmentations.sql
  datasets/idc/_images/generate_bq_views/queries/v5/dicom_all.sql
  datasets/idc/_images/generate_bq_views/queries/v5/dicom_metadata_curated.sql
  datasets/idc/_images/generate_bq_views/queries/v5/measurement_groups.sql
  datasets/idc/_images/generate_bq_views/queries/v5/qualitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v5/quantitative_measurements.sql
  datasets/idc/_images/generate_bq_views/queries/v5/segmentations.sql
  datasets/idc/_images/generate_bq_views/requirements.txt
  datasets/idc/_images/generate_bq_views/script.py
  datasets/idc/_terraform/idc_dataset.tf
  datasets/idc/_terraform/provider.tf
  datasets/idc/_terraform/variables.tf
  datasets/idc/copy_tcia_data/copy_tcia_data_dag.py
  datasets/idc/copy_tcia_data/pipeline.yaml
  datasets/idc/dataset.yaml
Labels: cla: yes
