Repository GoogleCloudPlatform/public-datasets-pipelines, pull requests merged in 2021-08, with the labels that each got.

#136 feat: Upgrade `usa_names` pipeline to use Airflow 2 operators
  datasets/usa_names/usa_1910_current/pipeline.yaml
  datasets/usa_names/usa_1910_current/usa_1910_current_dag.py
Labels: cleanup, data onboarding, cla: yes

#135 feat!: Upgrade dependencies to Airflow 2.1.1
  Pipfile
  Pipfile.lock
  README.md
  datasets/usa_names/usa_1910_current/pipeline.yaml
  datasets/usa_names/usa_1910_current/usa_1910_current_dag.py
  requirements-dev.txt
  scripts/deploy_dag.py
  scripts/generate_dag.py
Labels: documentation, feature request, cleanup, dependencies, cla: yes

#125 docs: Add best practices for percentage data and hierarchies
  README.md
Labels: documentation, cla: yes

#134 feat!: Adds support for Airflow 2 Cloud Composer environment and operators
  Pipfile
  Pipfile.lock
  README.md
  datasets/bls/cpsaat18/pipeline.yaml
  datasets/covid19_tracking/city_level_cases_and_deaths/pipeline.yaml
  datasets/covid19_tracking/covid_racial_data_tracker/pipeline.yaml
  datasets/covid19_tracking/national_testing_and_outcomes/pipeline.yaml
  datasets/covid19_tracking/state_facility_level_long_term_care/pipeline.yaml
  datasets/covid19_tracking/state_level_aggregate_long_term_care/pipeline.yaml
  datasets/covid19_tracking/state_level_cumulative_long_term_care/pipeline.yaml
  datasets/covid19_tracking/state_level_current_outbreak_long_term_care/pipeline.yaml
  datasets/covid19_tracking/state_screenshots/pipeline.yaml
  datasets/covid19_tracking/state_testing_and_outcomes/pipeline.yaml
  datasets/covid19_vaccination_access/vaccination_access_to_bq/pipeline.yaml
  datasets/covid19_vaccination_search_insights/covid19_vaccination_search_insights/pipeline.yaml
  datasets/google_dei/diversity_annual_report/pipeline.yaml
  datasets/google_trends/top_terms/pipeline.yaml
  datasets/iowa_liquor_sales_forecasting/2020_sales_train/pipeline.yaml
  datasets/iowa_liquor_sales_forecasting/2021_sales_predict/pipeline.yaml
  datasets/ml_datasets/penguins/pipeline.yaml
  datasets/usa_names/usa_1910_current/pipeline.yaml
  datasets/usa_names/usa_1910_current/usa_1910_current_dag.py
  datasets/vizgen_merfish/mouse_brain_map/pipeline.yaml
  requirements-dev.txt
  samples/pipeline.yaml
  scripts/dag_imports.json
  scripts/deploy_dag.py
  scripts/generate_dag.py
  tests/scripts/test_deploy_dag.py
  tests/scripts/test_generate_dag.py
Labels: documentation, feature request, cleanup, cla: yes

#141 docs: Revised Airflow DB initialization command
  README.md
Labels: cla: yes

#133 feat: Onboard Google Cloud Release Notes dataset
  datasets/google_cloud_release_notes/_terraform/google_cloud_release_notes_dataset.tf
  datasets/google_cloud_release_notes/_terraform/provider.tf
  datasets/google_cloud_release_notes/_terraform/release_notes_pipeline.tf
  datasets/google_cloud_release_notes/_terraform/variables.tf
  datasets/google_cloud_release_notes/dataset.yaml
  datasets/google_cloud_release_notes/release_notes/pipeline.yaml
  datasets/google_cloud_release_notes/release_notes/release_notes_dag.py
Labels: data onboarding, cla: yes

#130 feat: Onboard GEOS-FP dataset
  datasets/geos_fp/_images/rolling_copy/Dockerfile
  datasets/geos_fp/_images/rolling_copy/Pipfile
  datasets/geos_fp/_images/rolling_copy/requirements.txt
  datasets/geos_fp/_images/rolling_copy/script.py
  datasets/geos_fp/_terraform/geos_fp_dataset.tf
  datasets/geos_fp/_terraform/provider.tf
  datasets/geos_fp/_terraform/variables.tf
  datasets/geos_fp/copy_files_rolling_basis/copy_files_rolling_basis_dag.py
  datasets/geos_fp/copy_files_rolling_basis/pipeline.yaml
  datasets/geos_fp/dataset.yaml
Labels: data onboarding, cla: yes

#154 feat: Onboard advertiser_geo_spend table under Google political Ads dataset
  datasets/google_political_ads/_terraform/advertiser_geo_spend_pipeline.tf
  datasets/google_political_ads/advertiser_geo_spend/advertiser_geo_spend_dag.py
  datasets/google_political_ads/advertiser_geo_spend/pipeline.yaml
Labels: data onboarding, cla: yes

#157 chore: gitignore nested Pipfiles
  .gitignore
  datasets/covid19_italy/_images/run_csv_transform_kub/Pipfile
  datasets/geos_fp/_images/rolling_copy/Pipfile
  datasets/google_political_ads/_images/run_csv_transform_kub/Pipfile
  datasets/irs_990/_images/run_csv_transform_kub/Pipfile
Labels: cleanup, cla: yes
