Repository GoogleCloudPlatform/public-datasets-pipelines, pull requests merged in 2021-06, with the labels that each got.

#47 chore: Add leahecole as a code reviewer and approver
  OWNERS
Labels: documentation

#40 docs: Updated pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cleanup

#45 docs: Added Python and Airflow version requirements
  README.md
Labels: documentation

#44 fix: Fix renovatebot config based on #43
  renovate.json
Labels: bug, dependencies

#46 feat: Support deploying a single pipeline in a dataset
  README.md
  scripts/deploy_dag.py
  tests/scripts/test_deploy_dag.py
Labels: bug, documentation

#48 fix: Fixed renovate config
  renovate.json
Labels: bug, dependencies

#61 patch: BigQuery dataset description now shows up in *_dataset.tf files
  scripts/generate_terraform.py
  tests/scripts/test_generate_terraform.py
Labels: bug

#59 feat: Support BigQuery table descriptions
  samples/pipeline.yaml
  templates/terraform/google_bigquery_table.tf.jinja2
  tests/scripts/test_generate_terraform.py
Labels: documentation, feature request

#68 chore: Update pipeline.yaml with more operators
  datasets/vaccination_access/vaccination_access_to_bq/pipeline.yaml
Labels: data onboarding

#64 chore: Use `images` folder for README images
  README.md
  images/architecture.png
Labels: cleanup

#62 chore: Use Datasets for Google Cloud link
  README.md
Labels: documentation

#74 feat: Onboard COVID-19 Vaccination Access dataset
  datasets/covid19_vaccination_access/_terraform/covid19_vaccination_access_dataset.tf
  datasets/covid19_vaccination_access/_terraform/provider.tf
  datasets/covid19_vaccination_access/_terraform/vaccination_access_dataset.tf
  datasets/covid19_vaccination_access/_terraform/vaccination_access_to_bq_pipeline.tf
  datasets/covid19_vaccination_access/_terraform/variables.tf
  datasets/covid19_vaccination_access/dataset.yaml
  datasets/covid19_vaccination_access/vaccination_access_to_bq/pipeline.yaml
  datasets/covid19_vaccination_access/vaccination_access_to_bq/vaccination_access_to_bq_dag.py
Labels: data onboarding

#77 chore: adds goog-pegman as a contributor
  CONTRIBUTORS
Labels: documentation

#80 fix: Update vaccination_access table columns to facility_country_region_code
  datasets/covid19_vaccination_access/_terraform/vaccination_access_to_bq_pipeline.tf
  datasets/covid19_vaccination_access/vaccination_access_to_bq/pipeline.yaml
  datasets/covid19_vaccination_access/vaccination_access_to_bq/vaccination_access_to_bq_dag.py
Labels: bug, data onboarding

#85 feat: add Iowa liquor sales samples for Vertex AI Forecasting tutorial
  datasets/iowa_liquor_sales_forecasting/2020_sales_train/2020_sales_train_dag.py
  datasets/iowa_liquor_sales_forecasting/2020_sales_train/pipeline.yaml
  datasets/iowa_liquor_sales_forecasting/2021_sales_predict/2021_sales_predict_dag.py
  datasets/iowa_liquor_sales_forecasting/2021_sales_predict/pipeline.yaml
  datasets/iowa_liquor_sales_forecasting/_terraform/2020_sales_train_pipeline.tf
  datasets/iowa_liquor_sales_forecasting/_terraform/2021_sales_predict_pipeline.tf
  datasets/iowa_liquor_sales_forecasting/_terraform/iowa_liquor_sales_dataset.tf
  datasets/iowa_liquor_sales_forecasting/_terraform/iowa_liquor_sales_forecasting_dataset.tf
  datasets/iowa_liquor_sales_forecasting/_terraform/provider.tf
  datasets/iowa_liquor_sales_forecasting/_terraform/variables.tf
  datasets/iowa_liquor_sales_forecasting/dataset.yaml
Labels: data onboarding

#86 feat: Support BigQueryToBigQueryOperator
  samples/pipeline.yaml
  scripts/dag_imports.json
  scripts/generate_dag.py
Labels: feature request

#66 refactor: Improve tests for BQ dataset and table descriptions
  tests/scripts/test_generate_terraform.py
Labels: cleanup

#83 fix: Fix BigQuery dataset descriptions for `covid19_tracking` and `ml_datasets`
  datasets/covid19_tracking/_terraform/covid19_tracking_dataset.tf
  datasets/covid19_tracking/dataset.yaml
  datasets/ml_datasets/dataset.yaml
Labels: bug, cleanup

#94 docs: Added missing link to `pipeline.yaml` sample
  README.md
Labels: documentation

#95 docs: prepend `pipenv run` to the Python commands
  README.md
Labels: documentation

#91 fix: Allow DAG deploys without `variables.json`
  README.md
  scripts/deploy_dag.py
  tests/scripts/test_deploy_dag.py
Labels: bug, cleanup

#92 feat: Onboard Google Trends dataset for top N terms
  datasets/google_trends/_terraform/google_trends_dataset.tf
  datasets/google_trends/_terraform/provider.tf
  datasets/google_trends/_terraform/top_terms_pipeline.tf
  datasets/google_trends/_terraform/variables.tf
  datasets/google_trends/dataset.yaml
  datasets/google_trends/top_terms/pipeline.yaml
  datasets/google_trends/top_terms/top_terms_dag.py
Labels: data onboarding

#103 fix: Allow newline and quotes for BQ dataset and table descriptions
  templates/terraform/google_bigquery_dataset.tf.jinja2
  templates/terraform/google_bigquery_table.tf.jinja2
  tests/scripts/test_generate_terraform.py
Labels: bug

#105 feat: Onboard BLS - CPSAAT 2020 dataset
  datasets/bls/_terraform/bls_dataset.tf
  datasets/bls/_terraform/cpsaat18_pipeline.tf
  datasets/bls/_terraform/provider.tf
  datasets/bls/_terraform/variables.tf
  datasets/bls/cpsaat18/cpsaat18_dag.py
  datasets/bls/cpsaat18/pipeline.yaml
  datasets/bls/dataset.yaml
Labels: data onboarding

#111 feat: Onboard Google Diversity Annual Report 2021 dataset
  datasets/google_dei/_terraform/diversity_annual_report_pipeline.tf
  datasets/google_dei/_terraform/google_dei_dataset.tf
  datasets/google_dei/_terraform/google_diversity_dataset.tf
  datasets/google_dei/_terraform/provider.tf
  datasets/google_dei/_terraform/variables.tf
  datasets/google_dei/dataset.yaml
  datasets/google_dei/diversity_annual_report/diversity_annual_report_dag.py
  datasets/google_dei/diversity_annual_report/pipeline.yaml
Labels: data onboarding
