Repository GoogleCloudPlatform/public-datasets-pipelines, pull requests merged in 2021-09, with the labels that each got.

#158 feat: Onboard NOAA dataset
  datasets/noaa/_images/run_csv_transform_kub_gsod_stations/Dockerfile
  datasets/noaa/_images/run_csv_transform_kub_gsod_stations/Pipfile
  datasets/noaa/_images/run_csv_transform_kub_gsod_stations/csv_transform.py
  datasets/noaa/_images/run_csv_transform_kub_gsod_stations/requirements.txt
  datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/Dockerfile
  datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/Pipfile
  datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/csv_transform.py
  datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/requirements.txt
  datasets/noaa/_terraform/gsod_stations_pipeline.tf
  datasets/noaa/_terraform/lightning_strikes_by_year_pipeline.tf
  datasets/noaa/_terraform/noaa_dataset.tf
  datasets/noaa/_terraform/provider.tf
  datasets/noaa/_terraform/variables.tf
  datasets/noaa/dataset.yaml
  datasets/noaa/gsod_stations/gsod_stations_dag.py
  datasets/noaa/gsod_stations/pipeline.yaml
  datasets/noaa/lightning_strikes_by_year/lightning_strikes_by_year_dag.py
  datasets/noaa/lightning_strikes_by_year/pipeline.yaml
  datasets/noaa/noaa_variables.json
Labels: data onboarding, cla: yes

#153 feat: Support Dataflow operator and job requirements
  Pipfile
  Pipfile.lock
  requirements-dev.txt
  samples/pipeline.yaml
  scripts/dag_imports.json
Labels: feature request, cla: yes

#156 feat: Onboard Austin Bikeshare dataset
  datasets/austin_bikeshare/_images/run_csv_transform_kub/Dockerfile
  datasets/austin_bikeshare/_images/run_csv_transform_kub/csv_transform.py
  datasets/austin_bikeshare/_images/run_csv_transform_kub/requirements.txt
  datasets/austin_bikeshare/_terraform/austin_bikeshare_dataset.tf
  datasets/austin_bikeshare/_terraform/bikeshare_stations_pipeline.tf
  datasets/austin_bikeshare/_terraform/provider.tf
  datasets/austin_bikeshare/_terraform/variables.tf
  datasets/austin_bikeshare/bikeshare_stations/bikeshare_stations_dag.py
  datasets/austin_bikeshare/bikeshare_stations/pipeline.yaml
  datasets/austin_bikeshare/dataset.yaml
Labels: data onboarding, cla: yes

#170 chore: Ignore nested JSON files under `datasets`
  .gitignore
Labels: cleanup, cla: yes

#173 chore: delete `datasets/noaa` JSON variables file
  datasets/noaa/noaa_variables.json
Labels: cleanup, cla: yes

#180 chore: Adds node pool affinities for pipelines using KubernetesPodOperator
  datasets/austin_bikeshare/bikeshare_stations/bikeshare_stations_dag.py
  datasets/austin_bikeshare/bikeshare_stations/pipeline.yaml
  datasets/covid19_italy/data_by_province/data_by_province_dag.py
  datasets/covid19_italy/data_by_province/pipeline.yaml
  datasets/covid19_italy/data_by_region/data_by_region_dag.py
  datasets/covid19_italy/data_by_region/pipeline.yaml
  datasets/covid19_italy/national_trends/national_trends_dag.py
  datasets/covid19_italy/national_trends/pipeline.yaml
  datasets/google_political_ads/advertiser_declared_stats/advertiser_declared_stats_dag.py
  datasets/google_political_ads/advertiser_declared_stats/pipeline.yaml
  datasets/google_political_ads/advertiser_geo_spend/advertiser_geo_spend_dag.py
  datasets/google_political_ads/advertiser_geo_spend/pipeline.yaml
  datasets/google_political_ads/advertiser_stats/advertiser_stats_dag.py
  datasets/google_political_ads/advertiser_stats/pipeline.yaml
  datasets/google_political_ads/advertiser_weekly_spend/advertiser_weekly_spend_dag.py
  datasets/google_political_ads/advertiser_weekly_spend/pipeline.yaml
  datasets/google_political_ads/campaign_targeting/campaign_targeting_dag.py
  datasets/google_political_ads/campaign_targeting/pipeline.yaml
  datasets/google_political_ads/creative_stats/creative_stats_dag.py
  datasets/google_political_ads/creative_stats/pipeline.yaml
  datasets/google_political_ads/geo_spend/geo_spend_dag.py
  datasets/google_political_ads/geo_spend/pipeline.yaml
  datasets/google_political_ads/last_updated/last_updated_dag.py
  datasets/google_political_ads/last_updated/pipeline.yaml
  datasets/google_political_ads/top_keywords_history/pipeline.yaml
  datasets/google_political_ads/top_keywords_history/top_keywords_history_dag.py
  datasets/irs_990/irs_990_2014/irs_990_2014_dag.py
  datasets/irs_990/irs_990_2014/pipeline.yaml
  datasets/irs_990/irs_990_2015/irs_990_2015_dag.py
  datasets/irs_990/irs_990_2015/pipeline.yaml
  datasets/irs_990/irs_990_2016/irs_990_2016_dag.py
  datasets/irs_990/irs_990_2016/pipeline.yaml
  datasets/irs_990/irs_990_2017/irs_990_2017_dag.py
  datasets/irs_990/irs_990_2017/pipeline.yaml
  datasets/irs_990/irs_990_ez_2014/irs_990_ez_2014_dag.py
  datasets/irs_990/irs_990_ez_2014/pipeline.yaml
  datasets/irs_990/irs_990_ez_2015/irs_990_ez_2015_dag.py
  datasets/irs_990/irs_990_ez_2015/pipeline.yaml
  datasets/irs_990/irs_990_ez_2016/irs_990_ez_2016_dag.py
  datasets/irs_990/irs_990_ez_2016/pipeline.yaml
  datasets/irs_990/irs_990_ez_2017/irs_990_ez_2017_dag.py
  datasets/irs_990/irs_990_ez_2017/pipeline.yaml
  datasets/irs_990/irs_990_pf_2014/irs_990_pf_2014_dag.py
  datasets/irs_990/irs_990_pf_2014/pipeline.yaml
  datasets/irs_990/irs_990_pf_2015/irs_990_pf_2015_dag.py
  datasets/irs_990/irs_990_pf_2015/pipeline.yaml
  datasets/irs_990/irs_990_pf_2016/irs_990_pf_2016_dag.py
  datasets/irs_990/irs_990_pf_2016/pipeline.yaml
  datasets/noaa/gsod_stations/gsod_stations_dag.py
  datasets/noaa/gsod_stations/pipeline.yaml
  datasets/noaa/lightning_strikes_by_year/lightning_strikes_by_year_dag.py
  datasets/noaa/lightning_strikes_by_year/pipeline.yaml
  samples/pipeline.yaml
Labels: documentation, cleanup, cla: yes

#188 fix: Use patched `flask-openid` version to fix failing builds
  Pipfile
  Pipfile.lock
  requirements-dev.txt
Labels: cla: yes

#195 fix: Delete temp GCS objects generated by gsutil's parallel composite upload for `geos_fp` dataset
  datasets/geos_fp/_images/rolling_copy/script.py
  datasets/geos_fp/copy_files_rolling_basis/copy_files_rolling_basis_dag.py
  datasets/geos_fp/copy_files_rolling_basis/pipeline.yaml
Labels: bug, cla: yes

#197 chore: Ignore *.tfvars files in datasets folder
  .gitignore
Labels: cleanup, cla: yes
