Repository GoogleCloudPlatform/public-datasets-pipelines, pull requests merged in 2022-02, with the labels that each got.

#280 feat: Onboard Travel Sustainability dataset
  datasets/idc/_images/copy_bq_datasets/script.py
  datasets/travel_sustainability/_terraform/flight_emissions_pipeline.tf
  datasets/travel_sustainability/_terraform/metadata_pipeline.tf
  datasets/travel_sustainability/_terraform/provider.tf
  datasets/travel_sustainability/_terraform/travel_sustainability_dataset.tf
  datasets/travel_sustainability/_terraform/variables.tf
  datasets/travel_sustainability/dataset.yaml
  datasets/travel_sustainability/flight_emissions/flight_emissions_dag.py
  datasets/travel_sustainability/flight_emissions/pipeline.yaml
  datasets/travel_sustainability/metadata/metadata_dag.py
  datasets/travel_sustainability/metadata/pipeline.yaml
Labels: data onboarding

#286 chore: Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#285 fix: Update and fix `city_health_dashboard` dataset
  datasets/city_health_dashboard/chdb_data_city_all/chdb_data_city_all_dag.py
  datasets/city_health_dashboard/chdb_data_city_all/pipeline.yaml
  datasets/city_health_dashboard/chdb_data_tract_all/chdb_data_tract_all_dag.py
  datasets/city_health_dashboard/chdb_data_tract_all/pipeline.yaml
Labels: data onboarding

#291 cleanup: Reduce blank lines in BQ table Terraform and upgrade black formatter
  .github/workflows/python-lint.yaml
  Pipfile
  Pipfile.lock
  datasets/chicago_crime/pipelines/crime/crime_dag.py
  templates/terraform/google_bigquery_table.tf.jinja2
Labels: cleanup

#295 docs: Revised the README
  README.md
Labels: documentation

#287 feat: Onboard Imaging Data Commons (IDC) v7 dataset
  datasets/idc/infra/idc_dataset.tf
  datasets/idc/pipelines/_images/copy_bq_datasets/script.py
  datasets/idc/pipelines/_images/generate_bq_views/queries/current/dicom_derived_all.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/current/dicom_pivot_v7.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/dicom_all.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/dicom_metadata_curated.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/dicom_pivot_v7.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/measurement_groups.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/qualitative_measurements.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/quantitative_measurements.sql
  datasets/idc/pipelines/_images/generate_bq_views/queries/v7/segmentations.sql
  datasets/idc/pipelines/copy_tcia_data/copy_tcia_data_dag.py
  datasets/idc/pipelines/copy_tcia_data/pipeline.yaml
  datasets/idc/pipelines/dataset.yaml
Labels: data onboarding

#284 feat: Add a Query Snippet to calculate the average bike trip for each month
  datasets/san_francisco_bikeshare/docs/queries/average_trip_per_month/artifact.yaml
  datasets/san_francisco_bikeshare/docs/queries/average_trip_per_month/average_trip_per_month.sql
Labels: documentation

#300 cleanup: Remove local Airflow development
  scripts/deploy_dag.py
  tests/scripts/test_deploy_dag.py
Labels: feature request, cleanup

#296 chore: Removed personal project name from the notebook
  datasets/san_francisco_311/docs/tutorials/predict_weekly_calls/sf_311_weekly_calls_prediction.ipynb
Labels: documentation

#302 docs: Use Airflow's environment variables feature over shared variables
  README.md
Labels: documentation
